apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: "CDRO Actions"
inputs:
  url:
    description: 'CDRO URL'
    required: false
    default: 'https://sda.preview.cb-demos.io'
  username:
    description: 'CDRO Username'
    required: true
  user-token:
    description: 'CDRO User token'
    required: true
  project-name:
    description: 'project name'
    required: true
  release-name:
    description: 'release name'
    required: true
  parameters:   
    description: 'parameters as json'
    required: false
    default: '{}'


runs:
  using: composite
  steps:
    - id: invoke-cdro-action
      name: invoke-cdro-action
      uses: docker://fedora:39
      shell: sh
      run: |
        set -x
        echo "Show ENV"
        env
        echo "Show Disks"
        df -h
        echo "project-name: ${{ inputs.project-name }}"
        echo "release-name: ${{ inputs.release-name }}"
        echo "Variables: ${{ inputs.parameters }}"
        echo "${{ inputs.parameters }}" > data.json
        cat data.json
        echo "Run CURL"
        curl -k -X POST "${{ inputs.url }}/rest/v1.0/releases?projectName=${{ inputs.project-name }}&releaseName=${{ inputs.release-name }}" \
          -u ${{ inputs.username }}:${{ inputs.user-token }} \
          -H "accept: application/json" \
          -d @data.json